
cdna = '''
ATGGGCTTCGTGAGACAGATACAGCTTTTGCTCTGGAAGAACTGGACCCTGCGGAAAAGGCAAAAGATTCGCTTTGTGGTGGAACTCGTGTGGCCTTTAT
CTTTATTTCTGGTCTTGATCTGGTTAAGGAATGCCAACCCACTCTACAGCCATCATGAATGCCATTTCCCCAACAAGGCGATGCCCTCAGCAGGAATGCT
GCCGTGGCTCCAGGGGATCTTCTGCAATGTGAACAATCCCTGTTTTCAAAGCCCCACCCCAGGAGAATCTCCTGGAATTGTGTCAAACTATAACAACTCC
ATCTTGGCAAGGGTATATCGAGATTTTCAAGAACTCCTCATGAATGCACCAGAGAGCCAGCACCTTGGCCGTATTTGGACAGAGCTACACATCTTGTCCC
AATTCATGGACACCCTCCGGACTCACCCGGAGAGAATTGCAGGAAGAGGAATACGAATAAGGGATATCTTGAAAGATGAAGAAACACTGACACTATTTCT
CATTAAAAACATCGGCCTGTCTGACTCAGTGGTCTACCTTCTGATCAACTCTCAAGTCCGTCCAGAGCAGTTCGCTCATGGAGTCCCGGACCTGGCGCTG
AAGGACATCGCCTGCAGCGAGGCCCTCCTGGAGCGCTTCATCATCTTCAGCCAGAGACGCGGGGCAAAGACGGTGCGCTATGCCCTGTGCTCCCTCTCCC
AGGGCACCCTACAGTGGATAGAAGACACTCTGTATGCCAACGTGGACTTCTTCAAGCTCTTCCGTGTGCTTCCCACACTCCTAGACAGCCGTTCTCAAGG
TATCAATCTGAGATCTTGGGGAGGAATATTATCTGATATGTCACCAAGAATTCAAGAGTTTATCCATCGGCCGAGTATGCAGGACTTGCTGTGGGTGACC
AGGCCCCTCATGCAGAATGGTGGTCCAGAGACCTTTACAAAGCTGATGGGCATCCTGTCTGACCTCCTGTGTGGCTACCCCGAGGGAGGTGGCTCTCGGG
TGCTCTCCTTCAACTGGTATGAAGACAATAACTATAAGGCCTTTCTGGGGATTGACTCCACAAGGAAGGATCCTATCTATTCTTATGACAGAAGAACAAC
ATCCTTTTGTAATGCATTGATCCAGAGCCTGGAGTCAAATCCTTTAACCAAAATCGCTTGGAGGGCGGCAAAGCCTTTGCTGATGGGAAAAATCCTGTAC
ACTCCTGATTCACCTGCAGCACGAAGGATACTGAAGAATGCCAACTCAACTTTTGAAGAACTGGAACACGTTAGGAAGTTGGTCAAAGCCTGGGAAGAAG
TAGGGCCCCAGATCTGGTACTTCTTTGACAACAGCACACAGATGAACATGATCAGAGATACCCTGGGGAACCCAACAGTAAAAGACTTTTTGAATAGGCA
GCTTGGTGAAGAAGGTATTACTGCTGAAGCCATCCTAAACTTCCTCTACAAGGGCCCTCGGGAAAGCCAGGCTGACGACATGGCCAACTTCGACTGGAGG
GACATATTTAACATCACTGATCGCACCCTCCGCCTGGTCAATCAATACCTGGAGTGCTTGGTCCTGGATAAGTTTGAAAGCTACAATGATGAAACTCAGC
TCACCCAACGTGCCCTCTCTCTACTGGAGGAAAACATGTTCTGGGCCGGAGTGGTATTCCCTGACATGTATCCCTGGACCAGCTCTCTACCACCCCACGT
GAAGTATAAGATCCGAATGGACATAGACGTGGTGGAGAAAACCAATAAGATTAAAGACAGGTATTGGGATTCTGGTCCCAGAGCTGATCCCGTGGAAGAT
TTCCGGTACATCTGGGGCGGGTTTGCCTATCTGCAGGACATGGTTGAACAGGGGATCACAAGGAGCCAGGTGCAGGCGGAGGCTCCAGTTGGAATCTACC
TCCAGCAGATGCCCTACCCCTGCTTCGTGGACGATTCTTTCATGATCATCCTGAACCGCTGTTTCCCTATCTTCATGGTGCTGGCATGGATCTACTCTGT
CTCCATGACTGTGAAGAGCATCGTCTTGGAGAAGGAGTTGCGACTGAAGGAGACCTTGAAAAATCAGGGTGTCTCCAATGCAGTGATTTGGTGTACCTGG
TTCCTGGACAGCTTCTCCATCATGTCGATGAGCATCTTCCTCCTGACGATATTCATCATGCATGGAAGAATCCTACATTACAGCGACCCATTCATCCTCT
TCCTGTTCTTGTTGGCTTTCTCCACTGCCACCATCATGCTGTGCTTTCTGCTCAGCACCTTCTTCTCCAAGGCCAGTCTGGCAGCAGCCTGTAGTGGTGT
CATCTATTTCACCCTCTACCTGCCACACATCCTGTGCTTCGCCTGGCAGGACCGCATGACCGCTGAGCTGAAGAAGGCTGTGAGCTTACTGTCTCCGGTG
GCATTTGGATTTGGCACTGAGTACCTGGTTCGCTTTGAAGAGCAAGGCCTGGGGCTGCAGTGGAGCAACATCGGGAACAGTCCCACGGAAGGGGACGAAT
TCAGCTTCCTGCTGTCCATGCAGATGATGCTCCTTGATGCTGCTGTCTATGGCTTACTCGCTTGGTACCTTGATCAGGTGTTTCCAGGAGACTATGGAAC
CCCACTTCCTTGGTACTTTCTTCTACAAGAGTCGTATTGGCTTGGCGGTGAAGGGTGTTCAACCAGAGAAGAAAGAGCCCTGGAAAAGACCGAGCCCCTA
ACAGAGGAAACGGAGGATCCAGAGCACCCAGAAGGAATACACGACTCCTTCTTTGAACGTGAGCATCCAGGGTGGGTTCCTGGGGTATGCGTGAAGAATC
TGGTAAAGATTTTTGAGCCCTGTGGCCGGCCAGCTGTGGACCGTCTGAACATCACCTTCTACGAGAACCAGATCACCGCATTCCTGGGCCACAATGGAGC
TGGGAAAACCACCACCTTGTCCATCCTGACGGGTCTGTTGCCACCAACCTCTGGGACTGTGCTCGTTGGGGGAAGGGACATTGAAACCAGCCTGGATGCA
GTCCGGCAGAGCCTTGGCATGTGTCCACAGCACAACATCCTGTTCCACCACCTCACGGTGGCTGAGCACATGCTGTTCTATGCCCAGCTGAAAGGAAAGT
CCCAGGAGGAGGCCCAGCTGGAGATGGAAGCCATGTTGGAGGACACAGGCCTCCACCACAAGCGGAATGAAGAGGCTCAGGACCTATCAGGTGGCATGCA
GAGAAAGCTGTCGGTTGCCATTGCCTTTGTGGGAGATGCCAAGGTGGTGATTCTGGACGAACCCACCTCTGGGGTGGACCCTTACTCGAGACGCTCAATC
TGGGATCTGCTCCTGAAGTATCGCTCAGGCAGAACCATCATCATGTCCACTCACCACATGGACGAGGCCGACCTCCTTGGGGACCGCATTGCCATCATTG
CCCAGGGAAGGCTCTACTGCTCAGGCACCCCACTCTTCCTGAAGAACTGCTTTGGCACAGGCTTGTACTTAACCTTGGTGCGCAAGATGAAAAACATCCA
GAGCCAAAGGAAAGGCAGTGAGGGGACCTGCAGCTGCTCGTCTAAGGGTTTCTCCACCACGTGTCCAGCCCACGTCGATGACCTAACTCCAGAACAAGTC
CTGGATGGGGATGTAAATGAGCTGATGGATGTAGTTCTCCACCATGTTCCAGAGGCAAAGCTGGTGGAGTGCATTGGTCAAGAACTTATCTTCCTTCTTC
CAAATAAGAACTTCAAGCACAGAGCATATGCCAGCCTTTTCAGAGAGCTGGAGGAGACGCTGGCTGACCTTGGTCTCAGCAGTTTTGGAATTTCTGACAC
TCCCCTGGAAGAGATTTTTCTGAAGGTCACGGAGGATTCTGATTCAGGACCTCTGTTTGCGGGTGGCGCTCAGCAGAAAAGAGAAAACGTCAACCCCCGA
CACCCCTGCTTGGGTCCCAGAGAGAAGGCTGGACAGACACCCCAGGACTCCAATGTCTGCTCCCCAGGGGCGCCGGCTGCTCACCCAGAGGGCCAGCCTC
CCCCAGAGCCAGAGTGCCCAGGCCCGCAGCTCAACACGGGGACACAGCTGGTCCTCCAGCATGTGCAGGCGCTGCTGGTCAAGAGATTCCAACACACCAT
CCGCAGCCACAAGGACTTCCTGGCGCAGATCGTGCTCCCGGCTACCTTTGTGTTTTTGGCTCTGATGCTTTCTATTGTTATCCCTCCTTTTGGCGAATAC
CCCGCTTTGACCCTTCACCCCTGGATATATGGGCAGCAGTACACCTTCTTCAGCATGGATGAACCAGGCAGTGAGCAGTTCACGGTACTTGCAGACGTCC
TCCTGAATAAGCCAGGCTTTGGCAACCGCTGCCTGAAGGAAGGGTGGCTTCCGGAGTACCCCTGTGGCAACTCAACACCCTGGAAGACTCCTTCTGTGTC
CCCAAACATCACCCAGCTGTTCCAGAAGCAGAAATGGACACAGGTCAACCCTTCACCATCCTGCAGGTGCAGCACCAGGGAGAAGCTCACCATGCTGCCA
GAGTGCCCCGAGGGTGCCGGGGGCCTCCCGCCCCCCCAGAGAACACAGCGCAGCACGGAAATTCTACAAGACCTGACGGACAGGAACATCTCCGACTTCT
TGGTAAAAACGTATCCTGCTCTTATAAGAAGCAGCTTAAAGAGCAAATTCTGGGTCAATGAACAGAGGTATGGAGGAATTTCCATTGGAGGAAAGCTCCC
AGTCGTCCCCATCACGGGGGAAGCACTTGTTGGGTTTTTAAGCGACCTTGGCCGGATCATGAATGTGAGCGGGGGCCCTATCACTAGAGAGGCCTCTAAA
GAAATACCTGATTTCCTTAAACATCTAGAAACTGAAGACAACATTAAGGTGTGGTTTAATAACAAAGGCTGGCATGCCCTGGTCAGCTTTCTCAATGTGG
CCCACAACGCCATCTTACGGGCCAGCCTGCCTAAGGACAGGAGCCCCGAGGAGTATGGAATCACCGTCATTAGCCAACCCCTGAACCTGACCAAGGAGCA
GCTCTCAGAGATTACAGTGCTGACCACTTCAGTGGATGCTGTGGTTGCCATCTGCGTGATTTTCTCCATGTCCTTCGTCCCAGCCAGCTTTGTCCTTTAT
TTGATCCAGGAGCGGGTGAACAAATCCAAGCACCTCCAGTTTATCAGTGGAGTGAGCCCCACCACCTACTGGGTGACCAACTTCCTCTGGGACATCATGA
ATTATTCCGTGAGTGCTGGGCTGGTGGTGGGCATCTTCATCGGGTTTCAGAAGAAAGCCTACACTTCTCCAGAAAACCTTCCTGCCCTTGTGGCACTGCT
CCTGCTGTATGGATGGGCGGTCATTCCCATGATGTACCCAGCATCCTTCCTGTTTGATGTCCCCAGCACAGCCTATGTGGCTTTATCTTGTGCTAATCTG
TTCATCGGCATCAACAGCAGTGCTATTACCTTCATCTTGGAATTATTTGAGAATAACCGGACGCTGCTCAGGTTCAACGCCGTGCTGAGGAAGCTGCTCA
TTGTCTTCCCCCACTTCTGCCTGGGCCGGGGCCTCATTGACCTTGCACTGAGCCAGGCTGTGACAGATGTCTATGCCCGGTTTGGTGAGGAGCACTCTGC
AAATCCGTTCCACTGGGACCTGATTGGGAAGAACCTGTTTGCCATGGTGGTGGAAGGGGTGGTGTACTTCCTCCTGACCCTGCTGGTCCAGCGCCACTTC
TTCCTCTCCCAATGGATTGCCGAGCCCACTAAGGAGCCCATTGTTGATGAAGATGATGATGTGGCTGAAGAAAGACAAAGAATTATTACTGGTGGAAATA
AAACTGACATCTTAAGGCTACATGAACTAACCAAGATTTATCCAGGCACCTCCAGCCCAGCAGTGGACAGGCTGTGTGTCGGAGTTCGCCCTGGAGAGTG
CTTTGGCCTCCTGGGAGTGAATGGTGCCGGCAAAACAACCACATTCAAGATGCTCACTGGGGACACCACAGTGACCTCAGGGGATGCCACCGTAGCAGGC
AAGAGTATTTTAACCAATATTTCTGAAGTCCATCAAAATATGGGCTACTGTCCTCAGTTTGATGCAATTGATGAGCTGCTCACAGGACGAGAACATCTTT
ACCTTTATGCCCGGCTTCGAGGTGTACCAGCAGAAGAAATCGAAAAGGTTGCAAACTGGAGTATTAAGAGCCTGGGCCTGACTGTCTACGCCGACTGCCT
GGCTGGCACGTACAGTGGGGGCAACAAGCGGAAACTCTCCACAGCCATCGCACTCATTGGCTGCCCACCGCTGGTGCTGCTGGATGAGCCCACCACAGGG
ATGGACCCCCAGGCACGCCGCATGCTGTGGAACGTCATCGTGAGCATCATCAGAGAAGGGAGGGCTGTGGTCCTCACATCCCACAGCATGGAAGAATGTG
AGGCACTGTGTACCCGGCTGGCCATCATGGTAAAGGGCGCCTTTCGATGTATGGGCACCATTCAGCATCTCAAGTCCAAATTTGGAGATGGCTATATCGT
CACAATGAAGATCAAATCCCCGAAGGACGACCTGCTTCCTGACCTGAACCCTGTGGAGCAGTTCTTCCAGGGGAACTTCCCAGGCAGTGTGCAGAGGGAG
AGGCACTACAACATGCTCCAGTTCCAGGTCTCCTCCTCCTCCCTGGCGAGGATCTTCCAGCTCCTCCTCTCCCACAAGGACAGCCTGCTCATCGAGGAGT
ACTCAGTCACACAGACCACACTGGACCAGGTGTTTGTAAATTTTGCTAAACAGCAGACTGAAAGTCATGACCTCCCTCTGCACCCTCGAGCTGCTGGAGC
CAGTCGACAAGCCCAGGACTGA
'''

protein =  '''
MGFVRQIQLLLWKNWTLRKRQKIRFVVELVWPLSLFLVLIWLRNANPLYSHHECHFPNKAMPSAGMLPWLQGIFCNVNNPCFQSPTPGESPGIVSNYNNS
ILARVYRDFQELLMNAPESQHLGRIWTELHILSQFMDTLRTHPERIAGRGIRIRDILKDEETLTLFLIKNIGLSDSVVYLLINSQVRPEQFAHGVPDLAL
KDIACSEALLERFIIFSQRRGAKTVRYALCSLSQGTLQWIEDTLYANVDFFKLFRVLPTLLDSRSQGINLRSWGGILSDMSPRIQEFIHRPSMQDLLWVT
RPLMQNGGPETFTKLMGILSDLLCGYPEGGGSRVLSFNWYEDNNYKAFLGIDSTRKDPIYSYDRRTTSFCNALIQSLESNPLTKIAWRAAKPLLMGKILY
TPDSPAARRILKNANSTFEELEHVRKLVKAWEEVGPQIWYFFDNSTQMNMIRDTLGNPTVKDFLNRQLGEEGITAEAILNFLYKGPRESQADDMANFDWR
DIFNITDRTLRLVNQYLECLVLDKFESYNDETQLTQRALSLLEENMFWAGVVFPDMYPWTSSLPPHVKYKIRMDIDVVEKTNKIKDRYWDSGPRADPVED
FRYIWGGFAYLQDMVEQGITRSQVQAEAPVGIYLQQMPYPCFVDDSFMIILNRCFPIFMVLAWIYSVSMTVKSIVLEKELRLKETLKNQGVSNAVIWCTW
FLDSFSIMSMSIFLLTIFIMHGRILHYSDPFILFLFLLAFSTATIMLCFLLSTFFSKASLAAACSGVIYFTLYLPHILCFAWQDRMTAELKKAVSLLSPV
AFGFGTEYLVRFEEQGLGLQWSNIGNSPTEGDEFSFLLSMQMMLLDAAVYGLLAWYLDQVFPGDYGTPLPWYFLLQESYWLGGEGCSTREERALEKTEPL
TEETEDPEHPEGIHDSFFEREHPGWVPGVCVKNLVKIFEPCGRPAVDRLNITFYENQITAFLGHNGAGKTTTLSILTGLLPPTSGTVLVGGRDIETSLDA
VRQSLGMCPQHNILFHHLTVAEHMLFYAQLKGKSQEEAQLEMEAMLEDTGLHHKRNEEAQDLSGGMQRKLSVAIAFVGDAKVVILDEPTSGVDPYSRRSI
WDLLLKYRSGRTIIMSTHHMDEADLLGDRIAIIAQGRLYCSGTPLFLKNCFGTGLYLTLVRKMKNIQSQRKGSEGTCSCSSKGFSTTCPAHVDDLTPEQV
LDGDVNELMDVVLHHVPEAKLVECIGQELIFLLPNKNFKHRAYASLFRELEETLADLGLSSFGISDTPLEEIFLKVTEDSDSGPLFAGGAQQKRENVNPR
HPCLGPREKAGQTPQDSNVCSPGAPAAHPEGQPPPEPECPGPQLNTGTQLVLQHVQALLVKRFQHTIRSHKDFLAQIVLPATFVFLALMLSIVIPPFGEY
PALTLHPWIYGQQYTFFSMDEPGSEQFTVLADVLLNKPGFGNRCLKEGWLPEYPCGNSTPWKTPSVSPNITQLFQKQKWTQVNPSPSCRCSTREKLTMLP
ECPEGAGGLPPPQRTQRSTEILQDLTDRNISDFLVKTYPALIRSSLKSKFWVNEQRYGGISIGGKLPVVPITGEALVGFLSDLGRIMNVSGGPITREASK
EIPDFLKHLETEDNIKVWFNNKGWHALVSFLNVAHNAILRASLPKDRSPEEYGITVISQPLNLTKEQLSEITVLTTSVDAVVAICVIFSMSFVPASFVLY
LIQERVNKSKHLQFISGVSPTTYWVTNFLWDIMNYSVSAGLVVGIFIGFQKKAYTSPENLPALVALLLLYGWAVIPMMYPASFLFDVPSTAYVALSCANL
FIGINSSAITFILELFENNRTLLRFNAVLRKLLIVFPHFCLGRGLIDLALSQAVTDVYARFGEEHSANPFHWDLIGKNLFAMVVEGVVYFLLTLLVQRHF
FLSQWIAEPTKEPIVDEDDDVAEERQRIITGGNKTDILRLHELTKIYPGTSSPAVDRLCVGVRPGECFGLLGVNGAGKTTTFKMLTGDTTVTSGDATVAG
KSILTNISEVHQNMGYCPQFDAIDELLTGREHLYLYARLRGVPAEEIEKVANWSIKSLGLTVYADCLAGTYSGGNKRKLSTAIALIGCPPLVLLDEPTTG
MDPQARRMLWNVIVSIIREGRAVVLTSHSMEECEALCTRLAIMVKGAFRCMGTIQHLKSKFGDGYIVTMKIKSPKDDLLPDLNPVEQFFQGNFPGSVQRE
RHYNMLQFQVSSSSLARIFQLLLSHKDSLLIEEYSVTQTTLDQVFVNFAKQQTESHDLPLHPRAAGASRQAQD*
'''

acceptor_splice = {   1: 'CACAG',
    67: 'TTAGC',
    161: 'TCCAG',
    303: 'TAAAG',
    443: 'TACAG',
    571: 'TGTAG',
    769: 'TGCAG',
    859: 'TACAG',
    1100: 'CCTAG',
    1240: 'GGCAG',
    1357: 'TTTAG',
    1555: 'CCAAG',
    1761: 'TGCAG',
    1938: 'CTCAG',
    2161: 'TTTAG',
    2383: 'TTCAG',
    2588: 'TGCAG',
    2654: 'TTTAG',
    2744: 'TGCAG',
    2919: 'CCAAG',
    3051: 'TGCAG',
    3191: 'CCTAG',
    3329: 'TCCAG',
    3523: 'TGCAG',
    3608: 'TGCAG',
    3814: 'CCTAG',
    3863: 'GACAG',
    4129: 'AACAG',
    4254: 'CACAG',
    4353: 'TCTAG',
    4540: 'ATGAG',
    4635: 'CTCAG',
    4668: 'TTCAG',
    4774: 'GTCAG',
    4849: 'TTTAG',
    5019: 'TCTAG',
    5197: 'TGCAG',
    5313: 'CCGAG',
    5461: 'CACAG',
    5585: 'TTCAG',
    5715: 'CCCAG',
    5836: 'TCTAG',
    5899: 'TGCAG',
    6006: 'CCTAG',
    6148: 'TGCAG',
    6283: 'CCTAG',
    6387: 'CCCAG',
    6480: 'CACAG',
    6730: 'CCTAG',
    6817: 'TCTAG'}

donor_splice = {   0: 'GTAAC',
    66: 'GTAAG',
    160: 'GTAAG',
    302: 'GTAAG',
    442: 'GTAGG',
    570: 'GTAAG',
    768: 'GTGAG',
    858: 'GTAAG',
    1099: 'GTAAG',
    1239: 'GTANN',
    1356: 'GTAAG',
    1554: 'GTGAT',
    1760: 'GTGAG',
    1937: 'GTAAG',
    2160: 'GTGAG',
    2382: 'GTAAG',
    2587: 'GTGAG',
    2653: 'GTAAA',
    2743: 'GTGAG',
    2918: 'GTAAG',
    3050: 'GTGCT',
    3190: 'GTAAC',
    3328: 'GTAGG',
    3522: 'GTAAG',
    3607: 'GTAAA',
    3813: 'GTATG',
    3862: 'GTACT',
    4128: 'GTGCG',
    4253: 'GTAAG',
    4352: 'GTACC',
    4539: 'GTAAG',
    4634: 'GTAAG',
    4667: 'GTATG',
    4773: 'GTACT',
    4848: 'GTAAG',
    5018: 'GTAAG',
    5196: 'GTAAG',
    5312: 'GTGAG',
    5460: 'GTGGG',
    5584: 'GTACG',
    5714: 'GTAAG',
    5835: 'GTGGG',
    5898: 'GTGAG',
    6005: 'GTGAA',
    6147: 'GTAAC',
    6282: 'GCAAG',
    6386: 'GTAAG',
    6479: 'GCAAG',
    6729: 'GTACC',
    6816: 'TCTTT'}

def get_cdna():
	return cdna.replace("\n", "")
	
def get_protein():
	return protein.replace("\n", "")
	
def get_codons():
	return [cdna[i:i+3] for i in range(0,len(cdna),3)]
	
def get_backward_numbered_splice_acceptor(bdry_pos):
	cumulative_length = max(acceptor_splice.keys())
	return acceptor_splice.get(cumulative_length-bdry_pos, None)
	
def get_backward_numbered_splice_donor(bdry_pos):
	cumulative_length = max(donor_splice.keys())
	return donor_splice.get(cumulative_length-bdry_pos, None)



